"""A committed artifact no code path can write (ADR-073).

ADR-068's coverage run listed `lanes/calibrate_perf.py:record_calibration`
among six functions with zero executed statements. Triaged, it was the one
with consequence attached:

  * `benchmarks/perf_seeded/calibration.yaml` is COMMITTED, added by commit
    cbbd421 ("v0.24.0 — … the perf lane is CALIBRATED").
  * `lane_status()` reads it and reports `CALIBRATED`.
  * `record_calibration` is the only writer of it anywhere in the repository,
    and nothing called `record_calibration`.

So the lane's advertised status rested on a file that could not be
regenerated by any code path — only hand-edited. The reading was real; what
was missing was the ability to take it again, and any way for a reader to see
that the one on disk was taken ninety releases ago.

Two things are pinned here, and they are different in kind:

  1. **The write path exists and is reachable** — `avs perf-calibrate` runs
     the calibration and records it. Mechanism, testable directly.
  2. **The reading says which build it came from** — `lane_status()` names it,
     and names the current build when they differ. This is ADR-054's finding
     applied to a second reader: `avs cadence` reported "ok (4d)" over a bench
     result nine releases old, because days are a proxy that breaks exactly
     when releases outpace measurement.

⚠ No test here may write the real `CALIBRATION_FILE`. It is a committed
measurement; a test that overwrites it would replace a recorded reading with
one taken on CI hardware and call it a pass. Every test that exercises the
write path redirects the module constant to a tmp path first.
"""

from __future__ import annotations

import pathlib

import yaml
from typer.testing import CliRunner

from ai_venture_studio.cli import app
from ai_venture_studio.lanes import calibrate_perf

REPO = pathlib.Path(__file__).resolve().parents[1]
COMMITTED = REPO / "benchmarks" / "perf_seeded" / "calibration.yaml"


def _result(catch_rate: float = 1.0) -> calibrate_perf.CalibrationResult:
    return calibrate_perf.CalibrationResult(
        catch_rate=catch_rate, detection_factor=3.0,
        environment="loopback", parity="low",
        readings=[calibrate_perf.EndpointReading(
            defect="n_plus_one_query", p95_ms=7.0, control_p95_ms=0.8,
            degradation=8.75, caught=True)],
        note="fixture")


# ---------------------------------------------------------------------------
# The write path exists
# ---------------------------------------------------------------------------


def test_the_command_runs_the_calibration_and_records_it(tmp_path, monkeypatch):
    """The gap ADR-068 measured, closed: a command that produces the file.

    Entered through `CliRunner`, not by calling the function — ADR-068's own
    finding was that 42 of 78 commands were never entered by any test and the
    defect that started it (`bench-criterion`'s `NameError`) lived in the CLI
    wrapper, ten lines below where `--help` stops looking.
    """
    monkeypatch.setattr(calibrate_perf, "CALIBRATION_FILE", tmp_path / "cal.yaml")
    result = CliRunner().invoke(
        app, ["perf-calibrate", "--requests-per-endpoint", "5"]
    )
    assert result.exit_code == 0, result.output
    written = yaml.safe_load((tmp_path / "cal.yaml").read_text())["calibration"]
    assert written["readings"], "recorded a calibration with no readings in it"
    assert written["environment"] == "loopback"
    assert "recorded:" in result.output and "lane status:" in result.output


def test_dry_run_measures_without_writing(tmp_path, monkeypatch):
    """The measurement is cheap but it is still a measurement, and it
    REPLACES the reading on disk. `--dry-run` is how you look first."""
    target = tmp_path / "cal.yaml"
    monkeypatch.setattr(calibrate_perf, "CALIBRATION_FILE", target)
    result = CliRunner().invoke(
        app, ["perf-calibrate", "--requests-per-endpoint", "5", "--dry-run"]
    )
    assert result.exit_code == 0, result.output
    assert "catch rate" in result.output, "measured nothing and said so quietly"
    assert not target.exists(), "--dry-run wrote the file it promised not to"


def test_every_record_carries_the_build_it_was_taken_on(tmp_path, monkeypatch):
    from ai_venture_studio import __version__

    monkeypatch.setattr(calibrate_perf, "CALIBRATION_FILE", tmp_path / "cal.yaml")
    out = calibrate_perf.record_calibration(_result(), at="2026-08-22")
    assert yaml.safe_load(out.read_text())["calibration"]["avs_version"] == __version__


# ---------------------------------------------------------------------------
# The reading says where it came from
# ---------------------------------------------------------------------------


def test_the_status_names_the_build_and_flags_a_stale_one(tmp_path, monkeypatch):
    from ai_venture_studio import __version__

    target = tmp_path / "cal.yaml"
    monkeypatch.setattr(calibrate_perf, "CALIBRATION_FILE", target)
    target.write_text(yaml.safe_dump({"calibration": {
        **_result().model_dump(), "at": "2026-07-26", "avs_version": "0.24.0"}}))
    status = calibrate_perf.lane_status()
    assert "v0.24.0" in status, "the reading does not say which build took it"
    assert f"current build v{__version__}" in status, (
        "a reading from another build reads exactly like a current one"
    )


def test_a_current_reading_does_not_nag(tmp_path, monkeypatch):
    from ai_venture_studio import __version__

    target = tmp_path / "cal.yaml"
    monkeypatch.setattr(calibrate_perf, "CALIBRATION_FILE", target)
    target.write_text(yaml.safe_dump({"calibration": {
        **_result().model_dump(), "at": "2026-08-22",
        "avs_version": __version__}}))
    status = calibrate_perf.lane_status()
    assert f"v{__version__}" in status and "current build" not in status


def test_an_unstamped_reading_says_unrecorded_and_never_current(tmp_path, monkeypatch):
    """ADR-056's rule: absent must not resolve toward the reassuring answer.
    A file with no build key is one this code has never written; reading it as
    current would turn the oldest possible artifact into a fresh one."""
    target = tmp_path / "cal.yaml"
    monkeypatch.setattr(calibrate_perf, "CALIBRATION_FILE", target)
    target.write_text(yaml.safe_dump({"calibration": {
        **_result().model_dump(), "at": "2026-07-26"}}))
    status = calibrate_perf.lane_status()
    assert "unrecorded build" in status and "current build" in status


def test_a_stale_build_is_described_and_never_downgraded(tmp_path, monkeypatch):
    """Staleness is not a verdict. Nothing here knows whether the lane's
    behaviour moved between two builds, so demoting a real reading to
    PROVISIONAL on a version bump would be a guess wearing a verdict's
    clothes — and it would make `avs perf-calibrate` mandatory on every
    release for a lane nobody changed."""
    target = tmp_path / "cal.yaml"
    monkeypatch.setattr(calibrate_perf, "CALIBRATION_FILE", target)
    target.write_text(yaml.safe_dump({"calibration": {
        **_result().model_dump(), "at": "2020-01-01", "avs_version": "0.0.1"}}))
    assert calibrate_perf.lane_status().startswith("CALIBRATED")


def test_a_failed_calibration_is_still_provisional(tmp_path, monkeypatch):
    """The build stamp is additive. The 80% catch-rate bar that decides
    CALIBRATED vs PROVISIONAL is untouched by this change."""
    target = tmp_path / "cal.yaml"
    monkeypatch.setattr(calibrate_perf, "CALIBRATION_FILE", target)
    target.write_text(yaml.safe_dump({"calibration": {
        **_result(catch_rate=0.6).model_dump(), "at": "2026-08-22",
        "avs_version": "0.114.0"}}))
    assert calibrate_perf.lane_status() == "PROVISIONAL"


# ---------------------------------------------------------------------------
# The artifact actually on disk
# ---------------------------------------------------------------------------


def test_the_committed_reading_says_which_build_took_it():
    """Backfilled from git, not guessed: commit cbbd421 added this file and
    its subject is "v0.24.0 — … the perf lane is CALIBRATED"."""
    calibration = yaml.safe_load(COMMITTED.read_text())["calibration"]
    assert str(calibration["avs_version"]) == "0.24.0"
    assert calibration["at"] == "2026-07-26"
